pipeline {
    agent any

    stages {
        stage('Clone repo') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Mohammedsalman14/jenkins_project.git'
            }
        }
        stage('Install dependencies') {
            steps {
                dir('Flask_project_1') {
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }
        stage('Run tests') {
            steps {
                dir('Flask_project_1') {
                    sh 'pytest || echo "No tests found"'
                }
            }
        }
        stage('Start app') {
            steps {
                dir('Flask_project_1') {
                    // kill previous Flask if running
                    sh 'pkill -f "python3 app.py" || true'
                    
                    // start new Flask app
                    sh 'nohup python3 app.py > flask.log 2>&1 &'
                }
            }
        }
    }
    post {
        success {
            echo '✅ Deployment SUCCESS! Flask app is running.'
        }
        failure {
            echo '❌ Deployment FAILED. Check logs for details.'
        }
        always {
            echo '🔔 Pipeline finished. Check flask.log for any output.'
        }
    }
}
