pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Mohammedsalman14/jenkins_project.git'
            }
        }
        stage('Install dependencies') {
            steps {
                dir('Flask_project_1') {
                    sh '''
                        python3 -m venv ${VENV_DIR}
                        . ${VENV_DIR}/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run tests') {
            steps {
                dir('Flask_project_1') {
                    sh '''
                        . ${VENV_DIR}/bin/activate
                        pytest || echo "No tests found"
                    '''
                }
            }
        }
        stage('Start app') {
            steps {
                dir('Flask_project_1') {
                    sh '''
                        pkill -f "python app.py" || true
                        ${VENV_DIR}/bin/python app.py > flask.log 2>&1 &
                    '''
                }
            }
        }
    }
    post {
        success {
            echo '✅ Deployment SUCCESS! Flask app is running.'
        }
        failure {
            echo '❌ Deployment FAILED. Check logs for details.'
        }
        always {
            echo '🔔 Pipeline finished. Check flask.log for any output.'
        }
    }
}
